# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - WeatherData

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure_function'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Debug - show folder structure
      - name: List repository files
        run: ls -R

      # Install dependencies into .python_packages instead of venv
      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          mkdir -p .python_packages/lib/site-packages
          pip install --target=".python_packages/lib/site-packages" -r requirements.txt

      # Zip the package for deployment
      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../release.zip .
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip -d ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4F161C82C84C40DC92DDC5AAAD1EE1EC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_66754C1A1DA94550A7EB24D91DC9EB78 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B72CC1973C714ED5AA287DE5F6B04730 }}

      # Enable Oryx + remote build so Azure uses the correct runtime
      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'WeatherData'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          remote-build: true
        env:
          ML_API_URL: ${{ secrets.ML_API_URL }}